New-Upload-1755854042013/objects/Application_Visibility__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Permission_Set_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Permission Set Name</label>
        <referenceTo>Permission_Set_Admin__c</referenceTo>
        <relationshipLabel>Application Visibilities</relationshipLabel>
        <relationshipName>Application_Visibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Visible__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Visible</label>
        <type>Checkbox</type>
    </fields>
    <label>Application Visibility</label>
    <nameField>
        <displayFormat>AV-{0000}</displayFormat>
        <label>Application Visibility Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Visibilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

New-Upload-1755854042013/objects/Class_Access__c.object
<CustomObject>
    <fields>
        <fullName>Apex_Class__c</fullName>
        <label>Apex Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enabled</label>
        <type>Checkbox</type>
    </fields>
    <label>Class Access</label>
    <nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>Class Access Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Accesses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

New-Upload-1755854042013/objects/Field_Permission__c.object
<CustomObject>
    <fields>
        <fullName>Editable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Editable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Field_Name__c</fullName>
        <label>Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Permission_Set_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Permission Set Name</label>
        <referenceTo>Permission_Set_Admin__c</referenceTo>
        <relationshipLabel>Field Permissions</relationshipLabel>
        <relationshipName>Field_Permissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Readable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Readable</label>
        <type>Checkbox</type>
    </fields>
    <label>Field Permission</label>
    <nameField>
        <displayFormat>FP-{0000}</displayFormat>
        <label>Field Permission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Permissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

New-Upload-1755854042013/objects/Object_Permission__c.object
<CustomObject>
    <fields>
        <fullName>Allow_Create__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Allow Create</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Allow_Delete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Allow Delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Allow_Edit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Allow Edit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Allow_Read__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Allow Read</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Modify_All_Records__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Modify All Records</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Permission_Set_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Permission Set Name</label>
        <referenceTo>Permission_Set_Admin__c</referenceTo>
        <relationshipLabel>Object Permissions</relationshipLabel>
        <relationshipName>Object_Permissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>View_All_Fields__c</fullName>
        <defaultValue>false</defaultValue>
        <label>View All Fields</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>View_All_Records__c</fullName>
        <defaultValue>false</defaultValue>
        <label>View All Records</label>
        <type>Checkbox</type>
    </fields>
    <label>Object Permission</label>
    <nameField>
        <displayFormat>OP-{0000}</displayFormat>
        <label>Object Permission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Object Permissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

New-Upload-1755854042013/objects/Page_Access__c.object
<CustomObject>
    <fields>
        <fullName>Apex_Page__c</fullName>
        <label>Apex Page</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Permission_Set_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Permission Set Name</label>
        <referenceTo>Permission_Set_Admin__c</referenceTo>
        <relationshipLabel>Page Accesses</relationshipLabel>
        <relationshipName>Page_Accesses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Page Access</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>Page Access Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Page Accesses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

New-Upload-1755854042013/objects/Permission_Set_Admin__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_License__c</fullName>
        <label>User License</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Permission Set Admin</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Permission Set Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Permission Set Admins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

New-Upload-1755854042013/objects/Record_Type_Visibility__c.object
<CustomObject>
    <fields>
        <fullName>Record_Type__c</fullName>
        <label>Record Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Visible__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Visible</label>
        <type>Checkbox</type>
    </fields>
    <label>Record Type Visibility</label>
    <nameField>
        <displayFormat>RTV-{0000}</displayFormat>
        <label>Record Type Visibility Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Record Type Visibilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

New-Upload-1755854042013/objects/Tab_Setting__c.object
<CustomObject>
    <fields>
        <fullName>Visibility__c</fullName>
        <label>Visibility</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Tab Setting</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>Tab Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tab Settings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

New-Upload-1755854042013/objects/User_Permission__c.object
<CustomObject>
    <fields>
        <fullName>Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Permission_Name__c</fullName>
        <label>Permission Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Permission_Set_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Permission Set Name</label>
        <referenceTo>Permission_Set_Admin__c</referenceTo>
        <relationshipLabel>User Permissions</relationshipLabel>
        <relationshipName>User_Permissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Permission</label>
    <nameField>
        <displayFormat>UP-{0000}</displayFormat>
        <label>User Permission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Permissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

New-Upload-1755854042013/classes/PermissionSetMetadataManager.cls
public class PermissionSetMetadataManager {
    
    /**
     * Creates custom objects and fields to store permission set data
     * This method uses the Metadata API to create the necessary objects
     */
    public static void createPermissionSetObjects() {
        try {
            // Create the main Permission Set object
            createPermissionSetObject();
            
            // Create related objects for different permission types
            createApplicationVisibilityObject();
            createUserPermissionObject();
            createObjectPermissionObject();
            createFieldPermissionObject();
            createPageAccessObject();
            createClassAccessObject();
            createTabSettingObject();
            createRecordTypeVisibilityObject();
            
            System.debug('Successfully created all permission set objects');
            
        } catch (Exception e) {
            System.debug('Error creating permission set objects: ' + e.getMessage());
            throw new PermissionSetMetadataManagerException('Failed to create permission set objects: ' + e.getMessage());
        }
    }
    
    /**
     * Create the main Permission Set object
     */
    private static void createPermissionSetObject() {
        // This would use Metadata API to create the object
        // For demonstration, we'll create the object structure
        
        Map<String, Object> objectMetadata = new Map<String, Object>();
        objectMetadata.put('fullName', 'Permission_Set_Admin__c');
        objectMetadata.put('label', 'Permission Set Admin');
        objectMetadata.put('pluralLabel', 'Permission Set Admins');
        objectMetadata.put('nameField', new Map<String, Object>{
            'type' => 'Text',
            'label' => 'Permission Set Name'
        });
        objectMetadata.put('deploymentStatus', 'Deployed');
        objectMetadata.put('enableSharing', true);
        objectMetadata.put('enableBulkApi', true);
        objectMetadata.put('enableStreamingApi', true);
        objectMetadata.put('enableReports', true);
        objectMetadata.put('enableSearch', true);
        objectMetadata.put('enableHistory', false);
        objectMetadata.put('enableLicensing', false);
        
        // Add fields
        List<Map<String, Object>> fields = new List<Map<String, Object>>();
        
        // Description field
        fields.add(new Map<String, Object>{
            'fullName' => 'Permission_Set_Admin__c.Description__c',
            'label' => 'Description',
            'type' => 'TextArea',
            'length' => 32768,
            'visibleLines' => 3
        });
        
        // Label field
        fields.add(new Map<String, Object>{
            'fullName' => 'Permission_Set_Admin__c.Label__c',
            'label' => 'Label',
            'type' => 'Text',
            'length' => 255
        });
        
        // User License field
        fields.add(new Map<String, Object>{
            'fullName' => 'Permission_Set_Admin__c.User_License__c',
            'label' => 'User License',
            'type' => 'Text',
            'length' => 255
        });
        
        objectMetadata.put('fields', fields);
        
        System.debug('Permission Set Object Metadata: ' + objectMetadata);
    }
    
    /**
     * Create Application Visibility object
     */
    private static void createApplicationVisibilityObject() {
        Map<String, Object> objectMetadata = new Map<String, Object>();
        objectMetadata.put('fullName', 'Application_Visibility__c');
        objectMetadata.put('label', 'Application Visibility');
        objectMetadata.put('pluralLabel', 'Application Visibilities');
        objectMetadata.put('nameField', new Map<String, Object>{
            'type' => 'AutoNumber',
            'label' => 'Application Visibility Number',
            'displayFormat' => 'AV-{0000}'
        });
        objectMetadata.put('deploymentStatus', 'Deployed');
        objectMetadata.put('enableSharing', true);
        objectMetadata.put('enableBulkApi', true);
        objectMetadata.put('enableStreamingApi', true);
        objectMetadata.put('enableReports', true);
        objectMetadata.put('enableSearch', true);
        objectMetadata.put('enableHistory', false);
        objectMetadata.put('enableLicensing', false);
        
        // Add fields
        List<Map<String, Object>> fields = new List<Map<String, Object>>();
        
        // Permission Set Name (Lookup)
        fields.add(new Map<String, Object>{
            'fullName' => 'Application_Visibility__c.Permission_Set_Name__c',
            'label' => 'Permission Set Name',
            'type' => 'Lookup',
            'referenceTo' => 'Permission_Set_Admin__c',
            'relationshipName' => 'Application_Visibilities',
            'relationshipLabel' => 'Application Visibilities',
            'deleteConstraint' => 'SetNull'
        });
        
        // Application field
        fields.add(new Map<String, Object>{
            'fullName' => 'Application_Visibility__c.Application__c',
            'label' => 'Application',
            'type' => 'Text',
            'length' => 255
        });
        
        // Visible field
        fields.add(new Map<String, Object>{
            'fullName' => 'Application_Visibility__c.Visible__c',
            'label' => 'Visible',
            'type' => 'Checkbox',
            'defaultValue' => false
        });
        
        objectMetadata.put('fields', fields);
        
        System.debug('Application Visibility Object Metadata: ' + objectMetadata);
    }
    
    /**
     * Create User Permission object
     */
    private static void createUserPermissionObject() {
        Map<String, Object> objectMetadata = new Map<String, Object>();
        objectMetadata.put('fullName', 'User_Permission__c');
        objectMetadata.put('label', 'User Permission');
        objectMetadata.put('pluralLabel', 'User Permissions');
        objectMetadata.put('nameField', new Map<String, Object>{
            'type' => 'AutoNumber',
            'label' => 'User Permission Number',
            'displayFormat' => 'UP-{0000}'
        });
        objectMetadata.put('deploymentStatus', 'Deployed');
        objectMetadata.put('enableSharing', true);
        objectMetadata.put('enableBulkApi', true);
        objectMetadata.put('enableStreamingApi', true);
        objectMetadata.put('enableReports', true);
        objectMetadata.put('enableSearch', true);
        objectMetadata.put('enableHistory', false);
        objectMetadata.put('enableLicensing', false);
        
        // Add fields
        List<Map<String, Object>> fields = new List<Map<String, Object>>();
        
        // Permission Set Name (Lookup)
        fields.add(new Map<String, Object>{
            'fullName' => 'User_Permission__c.Permission_Set_Name__c',
            'label' => 'Permission Set Name',
            'type' => 'Lookup',
            'referenceTo' => 'Permission_Set_Admin__c',
            'relationshipName' => 'User_Permissions',
            'relationshipLabel' => 'User Permissions',
            'deleteConstraint' => 'SetNull'
        });
        
        // Permission Name field
        fields.add(new Map<String, Object>{
            'fullName' => 'User_Permission__c.Permission_Name__c',
            'label' => 'Permission Name',
            'type' => 'Text',
            'length' => 255
        });
        
        // Enabled field
        fields.add(new Map<String, Object>{
            'fullName' => 'User_Permission__c.Enabled__c',
            'label' => 'Enabled',
            'type' => 'Checkbox',
            'defaultValue' => false
        });
        
        objectMetadata.put('fields', fields);
        
        System.debug('User Permission Object Metadata: ' + objectMetadata);
    }
    
    /**
     * Create Object Permission object
     */
    private static void createObjectPermissionObject() {
        Map<String, Object> objectMetadata = new Map<String, Object>();
        objectMetadata.put('fullName', 'Object_Permission__c');
        objectMetadata.put('label', 'Object Permission');
        objectMetadata.put('pluralLabel', 'Object Permissions');
        objectMetadata.put('nameField', new Map<String, Object>{
            'type' => 'AutoNumber',
            'label' => 'Object Permission Number',
            'displayFormat' => 'OP-{0000}'
        });
        objectMetadata.put('deploymentStatus', 'Deployed');
        objectMetadata.put('enableSharing', true);
        objectMetadata.put('enableBulkApi', true);
        objectMetadata.put('enableStreamingApi', true);
        objectMetadata.put('enableReports', true);
        objectMetadata.put('enableSearch', true);
        objectMetadata.put('enableHistory', false);
        objectMetadata.put('enableLicensing', false);
        
        // Add fields
        List<Map<String, Object>> fields = new List<Map<String, Object>>();
        
        // Permission Set Name (Lookup)
        fields.add(new Map<String, Object>{
            'fullName' => 'Object_Permission__c.Permission_Set_Name__c',
            'label' => 'Permission Set Name',
            'type' => 'Lookup',
            'referenceTo' => 'Permission_Set_Admin__c',
            'relationshipName' => 'Object_Permissions',
            'relationshipLabel' => 'Object Permissions',
            'deleteConstraint' => 'SetNull'
        });
        
        // Object Name field
        fields.add(new Map<String, Object>{
            'fullName' => 'Object_Permission__c.Object_Name__c',
            'label' => 'Object Name',
            'type' => 'Text',
            'length' => 255
        });
        
        // Permission fields
        fields.add(new Map<String, Object>{
            'fullName' => 'Object_Permission__c.Allow_Create__c',
            'label' => 'Allow Create',
            'type' => 'Checkbox',
            'defaultValue' => false
        });
        
        fields.add(new Map<String, Object>{
            'fullName' => 'Object_Permission__c.Allow_Delete__c',
            'label' => 'Allow Delete',
            'type' => 'Checkbox',
            'defaultValue' => false
        });
        
        fields.add(new Map<String, Object>{
            'fullName' => 'Object_Permission__c.Allow_Edit__c',
            'label' => 'Allow Edit',
            'type' => 'Checkbox',
            'defaultValue' => false
        });
        
        fields.add(new Map<String, Object>{
            'fullName' => 'Object_Permission__c.Allow_Read__c',
            'label' => 'Allow Read',
            'type' => 'Checkbox',
            'defaultValue' => false
        });
        
        fields.add(new Map<String, Object>{
            'fullName' => 'Object_Permission__c.View_All_Records__c',
            'label' => 'View All Records',
            'type' => 'Checkbox',
            'defaultValue' => false
        });
        
        fields.add(new Map<String, Object>{
            'fullName' => 'Object_Permission__c.Modify_All_Records__c',
            'label' => 'Modify All Records',
            'type' => 'Checkbox',
            'defaultValue' => false
        });
        
        fields.add(new Map<String, Object>{
            'fullName' => 'Object_Permission__c.View_All_Fields__c',
            'label' => 'View All Fields',
            'type' => 'Checkbox',
            'defaultValue' => false
        });
        
        objectMetadata.put('fields', fields);
        
        System.debug('Object Permission Object Metadata: ' + objectMetadata);
    }
    
    /**
     * Create Field Permission object
     */
    private static void createFieldPermissionObject() {
        Map<String, Object> objectMetadata = new Map<String, Object>();
        objectMetadata.put('fullName', 'Field_Permission__c');
        objectMetadata.put('label', 'Field Permission');
        objectMetadata.put('pluralLabel', 'Field Permissions');
        objectMetadata.put('nameField', new Map<String, Object>{
            'type' => 'AutoNumber',
            'label' => 'Field Permission Number',
            'displayFormat' => 'FP-{0000}'
        });
        objectMetadata.put('deploymentStatus', 'Deployed');
        objectMetadata.put('enableSharing', true);
        objectMetadata.put('enableBulkApi', true);
        objectMetadata.put('enableStreamingApi', true);
        objectMetadata.put('enableReports', true);
        objectMetadata.put('enableSearch', true);
        objectMetadata.put('enableHistory', false);
        objectMetadata.put('enableLicensing', false);
        
        // Add fields
        List<Map<String, Object>> fields = new List<Map<String, Object>>();
        
        // Permission Set Name (Lookup)
        fields.add(new Map<String, Object>{
            'fullName' => 'Field_Permission__c.Permission_Set_Name__c',
            'label' => 'Permission Set Name',
            'type' => 'Lookup',
            'referenceTo' => 'Permission_Set_Admin__c',
            'relationshipName' => 'Field_Permissions',
            'relationshipLabel' => 'Field Permissions',
            'deleteConstraint' => 'SetNull'
        });
        
        // Field Name field
        fields.add(new Map<String, Object>{
            'fullName' => 'Field_Permission__c.Field_Name__c',
            'label' => 'Field Name',
            'type' => 'Text',
            'length' => 255
        });
        
        // Permission fields
        fields.add(new Map<String, Object>{
            'fullName' => 'Field_Permission__c.Editable__c',
            'label' => 'Editable',
            'type' => 'Checkbox',
            'defaultValue' => false
        });
        
        fields.add(new Map<String, Object>{
            'fullName' => 'Field_Permission__c.Readable__c',
            'label' => 'Readable',
            'type' => 'Checkbox',
            'defaultValue' => false
        });
        
        objectMetadata.put('fields', fields);
        
        System.debug('Field Permission Object Metadata: ' + objectMetadata);
    }
    
    /**
     * Create Page Access object
     */
    private static void createPageAccessObject() {
        Map<String, Object> objectMetadata = new Map<String, Object>();
        objectMetadata.put('fullName', 'Page_Access__c');
        objectMetadata.put('label', 'Page Access');
        objectMetadata.put('pluralLabel', 'Page Accesses');
        objectMetadata.put('nameField', new Map<String, Object>{
            'type' => 'AutoNumber',
            'label' => 'Page Access Number',
            'displayFormat' => 'PA-{0000}'
        });
        objectMetadata.put('deploymentStatus', 'Deployed');
        objectMetadata.put('enableSharing', true);
        objectMetadata.put('enableBulkApi', true);
        objectMetadata.put('enableStreamingApi', true);
        objectMetadata.put('enableReports', true);
        objectMetadata.put('enableSearch', true);
        objectMetadata.put('enableHistory', false);
        objectMetadata.put('enableLicensing', false);
        
        // Add fields
        List<Map<String, Object>> fields = new List<Map<String, Object>>();
        
        // Permission Set Name (Lookup)
        fields.add(new Map<String, Object>{
            'fullName' => 'Page_Access__c.Permission_Set_Name__c',
            'label' => 'Permission Set Name',
            'type' => 'Lookup',
            'referenceTo' => 'Permission_Set_Admin__c',
            'relationshipName' => 'Page_Accesses',
            'relationshipLabel' => 'Page Accesses',
            'deleteConstraint' => 'SetNull'
        });
        
        // Apex Page field
        fields.add(new Map<String, Object>{
            'fullName' => 'Page_Access__c.Apex_Page__c',
            'label' => 'Apex Page',
            'type' => 'Text',
            'length' => 255
        });
        
        // Enabled field
        fields.add(new Map<String, Object>{
            'fullName' => 'Page_Access__c.Enabled__c',
            'label' => 'Enabled',
            'type' => 'Checkbox',
            'defaultValue' => false
        });
        
        objectMetadata.put('fields', fields);
        
        System.debug('Page Access Object Metadata: ' + objectMetadata);
    }
    
    /**
     * Create Class Access object
     */
    private static void createClassAccessObject() {
        Map<String, Object> objectMetadata = new Map<String, Object>();
        objectMetadata.put('fullName', 'Class_Access__c');
        objectMetadata.put('label', 'Class Access');
        objectMetadata.put('pluralLabel', 'Class Accesses');
        objectMetadata.put('nameField', new Map<String, Object>{
            'type' => 'AutoNumber',
            'label' => 'Class Access Number',
            'displayFormat' => 'CA-{0000}'
        });
        objectMetadata.put('deploymentStatus', 'Deployed');
        objectMetadata.put('enableSharing', true);
        objectMetadata.put('enableBulkApi', true);
        objectMetadata.put('enableStreamingApi', true);
        objectMetadata.put('enableReports', true);
        objectMetadata.put('enableSearch', true);
        objectMetadata.put('enableHistory', false);
        objectMetadata.put('enableLicensing', false);
        
        // Add fields
        List<Map<String, Object>> fields = new List<Map<String, Object>>();
        
        // Permission Set Name (Lookup)
        fields.add(new Map<String, Object>{
            'fullName' => 'Class_Access__c.Permission_Set_Name__c',
            'label' => 'Permission Set Name',
            'type' => 'Lookup',
            'referenceTo' => 'Permission_Set_Admin__c',
            'relationshipName' => 'Class_Accesses',
            'relationshipLabel' => 'Class Accesses',
            'deleteConstraint' => 'SetNull'
        });
        
        // Apex Class field
        fields.add(new Map<String, Object>{
            'fullName' => 'Class_Access__c.Apex_Class__c',
            'label' => 'Apex Class',
            'type' => 'Text',
            'length' => 255
        });
        
        // Enabled field
        fields.add(new Map<String, Object>{
            'fullName' => 'Class_Access__c.Enabled__c',
            'label' => 'Enabled',
            'type' => 'Checkbox',
            'defaultValue' => false
        });
        
        objectMetadata.put('fields', fields);
        
        System.debug('Class Access Object Metadata: ' + objectMetadata);
    }
    
    /**
     * Create Tab Setting object
     */
    private static void createTabSettingObject() {
        Map<String, Object> objectMetadata = new Map<String, Object>();
        objectMetadata.put('fullName', 'Tab_Setting__c');
        objectMetadata.put('label', 'Tab Setting');
        objectMetadata.put('pluralLabel', 'Tab Settings');
        objectMetadata.put('nameField', new Map<String, Object>{
            'type' => 'AutoNumber',
            'label' => 'Tab Setting Number',
            'displayFormat' => 'TS-{0000}'
        });
        objectMetadata.put('deploymentStatus', 'Deployed');
        objectMetadata.put('enableSharing', true);
        objectMetadata.put('enableBulkApi', true);
        objectMetadata.put('enableStreamingApi', true);
        objectMetadata.put('enableReports', true);
        objectMetadata.put('enableSearch', true);
        objectMetadata.put('enableHistory', false);
        objectMetadata.put('enableLicensing', false);
        
        // Add fields
        List<Map<String, Object>> fields = new List<Map<String, Object>>();
        
        // Permission Set Name (Lookup)
        fields.add(new Map<String, Object>{
            'fullName' => 'Tab_Setting__c.Permission_Set_Name__c',
            'label' => 'Permission Set Name',
            'type' => 'Lookup',
            'referenceTo' => 'Permission_Set_Admin__c',
            'relationshipName' => 'Tab_Settings',
            'relationshipLabel' => 'Tab Settings',
            'deleteConstraint' => 'SetNull'
        });
        
        // Tab Name field
        fields.add(new Map<String, Object>{
            'fullName' => 'Tab_Setting__c.Tab_Name__c',
            'label' => 'Tab Name',
            'type' => 'Text',
            'length' => 255
        });
        
        // Visibility field
        fields.add(new Map<String, Object>{
            'fullName' => 'Tab_Setting__c.Visibility__c',
            'label' => 'Visibility',
            'type' => 'Text',
            'length' => 255
        });
        
        objectMetadata.put('fields', fields);
        
        System.debug('Tab Setting Object Metadata: ' + objectMetadata);
    }
    
    /**
     * Create Record Type Visibility object
     */
    private static void createRecordTypeVisibilityObject() {
        Map<String, Object> objectMetadata = new Map<String, Object>();
        objectMetadata.put('fullName', 'Record_Type_Visibility__c');
        objectMetadata.put('label', 'Record Type Visibility');
        objectMetadata.put('pluralLabel', 'Record Type Visibilities');
        objectMetadata.put('nameField', new Map<String, Object>{
            'type' => 'AutoNumber',
            'label' => 'Record Type Visibility Number',
            'displayFormat' => 'RTV-{0000}'
        });
        objectMetadata.put('deploymentStatus', 'Deployed');
        objectMetadata.put('enableSharing', true);
        objectMetadata.put('enableBulkApi', true);
        objectMetadata.put('enableStreamingApi', true);
        objectMetadata.put('enableReports', true);
        objectMetadata.put('enableSearch', true);
        objectMetadata.put('enableHistory', false);
        objectMetadata.put('enableLicensing', false);
        
        // Add fields
        List<Map<String, Object>> fields = new List<Map<String, Object>>();
        
        // Permission Set Name (Lookup)
        fields.add(new Map<String, Object>{
            'fullName' => 'Record_Type_Visibility__c.Permission_Set_Name__c',
            'label' => 'Permission Set Name',
            'type' => 'Lookup',
            'referenceTo' => 'Permission_Set_Admin__c',
            'relationshipName' => 'Record_Type_Visibilities',
            'relationshipLabel' => 'Record Type Visibilities',
            'deleteConstraint' => 'SetNull'
        });
        
        // Record Type field
        fields.add(new Map<String, Object>{
            'fullName' => 'Record_Type_Visibility__c.Record_Type__c',
            'label' => 'Record Type',
            'type' => 'Text',
            'length' => 255
        });
        
        // Visible field
        fields.add(new Map<String, Object>{
            'fullName' => 'Record_Type_Visibility__c.Visible__c',
            'label' => 'Visible',
            'type' => 'Checkbox',
            'defaultValue' => false
        });
        
        objectMetadata.put('fields', fields);
        
        System.debug('Record Type Visibility Object Metadata: ' + objectMetadata);
    }
    
    /**
     * Custom exception class
     */
    public class PermissionSetMetadataManagerException extends Exception {}
}