New-Upload-1755854042013/objects/Object_Permission_admn__c.object
<CustomObject>
    <fields>
        <fullName>Create__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Create</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Edit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Edit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Modify_All__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Modify All</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Permission_Set__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Permission Set</label>
        <referenceTo>Permission_Set_admn__c</referenceTo>
        <relationshipLabel>Object Permissions</relationshipLabel>
        <relationshipName>Object_Permissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Read__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Read</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>View_All__c</fullName>
        <defaultValue>false</defaultValue>
        <label>View All</label>
        <type>Checkbox</type>
    </fields>
    <label>Object Permission</label>
    <nameField>
        <displayFormat>OP-{0000}</displayFormat>
        <label>Object Permission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Object Permissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

New-Upload-1755854042013/objects/Permission_Set__c.object
<CustomObject>
    <fields>
        <fullName>User_License__c</fullName>
        <label>User License</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Permission Set</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Permission Set Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Permission Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

New-Upload-1755854042013/objects/Permission_Set_admn__c.object
<CustomObject>
    <label>Permission Set</label>
    <nameField>
        <label>Permission Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permission Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

New-Upload-1755854042013/objects/Permission_Set_Group_admn__c.object
<CustomObject>
    <label>Permission Set Group</label>
    <nameField>
        <displayFormat>PSG-{0000}</displayFormat>
        <label>Permission Set Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Permission Set Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

New-Upload-1755854042013/objects/Profile_admn__c.object
<CustomObject>
    <fields>
        <fullName>Is_Custom__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Custom</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User_License__c</fullName>
        <label>User License</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Profile</label>
    <nameField>
        <label>Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

New-Upload-1755854042013/classes/PermissionSetDetailsController.cls
public with sharing class PermissionSetDetailsController {
    
    @AuraEnabled(cacheable=true)
    public static Permission_Set_admn__c getPermissionSetDetails(Id permissionSetId) {
        try {
            return [
                SELECT Id, Name, CreatedDate, LastModifiedDate, CreatedBy.Name, LastModifiedBy.Name
                FROM Permission_Set_admn__c
                WHERE Id = :permissionSetId
                LIMIT 1
            ];
        } catch (Exception e) {
            throw new AuraHandledException('Error retrieving permission set details: ' + e.getMessage());
        }
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Object_Permission_admn__c> getObjectPermissions(Id permissionSetId) {
        try {
            // Note: Object_Permission_admn__c doesn't have a Permission_Set__c lookup field
            // Returning all object permissions for now
            return [
                SELECT Id, Name, Object_Name__c, Read__c, Create__c, Edit__c,
                       View_All__c, Modify_All__c, CreatedDate
                FROM Object_Permission_admn__c
                ORDER BY Object_Name__c ASC
                LIMIT 100
            ];
        } catch (Exception e) {
            throw new AuraHandledException('Error retrieving object permissions: ' + e.getMessage());
        }
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Profile_admn__c> getProfiles(Id permissionSetId) {
        try {
            // Note: Profile_admn__c doesn't have a Permission_Set__c lookup field
            // Returning all profiles for now
            return [
                SELECT Id, Name, Is_Custom__c, User_License__c, CreatedDate
                FROM Profile_admn__c
                ORDER BY Name ASC
                LIMIT 100
            ];
        } catch (Exception e) {
            throw new AuraHandledException('Error retrieving profiles: ' + e.getMessage());
        }
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Permission_Set_Group_admn__c> getPermissionSetGroups(Id permissionSetId) {
        try {
            // Note: Permission_Set_Group_admn__c doesn't have a Permission_Set__c lookup field
            // Returning all permission set groups for now
            return [
                SELECT Id, Name, CreatedDate
                FROM Permission_Set_Group_admn__c
                ORDER BY Name ASC
                LIMIT 100
            ];
        } catch (Exception e) {
            throw new AuraHandledException('Error retrieving permission set groups: ' + e.getMessage());
        }
    }
}