New-Upload-1755854042013/objects/Profiles__c.object
<CustomObject>
    <fields>
        <fullName>Custom__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Custom</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Permission_Editable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Field Permission Editable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Field_Permission_Field__c</fullName>
        <label>Field Permission Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Permission_Readable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Field Permission Readable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Object_Permission_AllowCreate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Object Permission Allow Create</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Object_Permission_AllowDelete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Object Permission Allow Delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Object_Permission_AllowEdit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Object Permission Allow Edit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Object_Permission_AllowRead__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Object Permission Allow Read</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Object_Permission_ModifyAllRecords__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Object Permission Modify All Records</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Object_Permission_Object__c</fullName>
        <label>Object Permission Object</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Permission_ViewAllFields__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Object Permission View All Fields</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Object_Permission_ViewAllRecords__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Object Permission View All Records</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tab_Visibility_Tab__c</fullName>
        <label>Tab Visibility Tab</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tab_Visibility_Visibility__c</fullName>
        <label>Tab Visibility Visibility</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tag_Types__c</fullName>
        <label>Tag Types</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>fieldPermissions</fullName>
                </value>
                <value>
                    <fullName>objectPermissions</fullName>
                </value>
                <value>
                    <fullName>tabVisibilities</fullName>
                </value>
                <value>
                    <fullName>userPermissions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_License__c</fullName>
        <label>User License</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Permission_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>User Permission Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User_Permission_Name__c</fullName>
        <label>User Permission Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Profiles</label>
    <nameField>
        <displayFormat>Profiles-{0000}</displayFormat>
        <label>Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

New-Upload-1755854042013/classes/ProfileXMLProcessor.cls
public class ProfileXMLProcessor {
    
    // XML parsing utility class
    public class ProfileData {
        public String description;
        public String userLicense;
        public Boolean custom;
        public List<FieldPermission> fieldPermissions;
        public List<ObjectPermission> objectPermissions;
        public List<TabVisibility> tabVisibilities;
        public List<UserPermission> userPermissions;
        
        public ProfileData() {
            fieldPermissions = new List<FieldPermission>();
            objectPermissions = new List<ObjectPermission>();
            tabVisibilities = new List<TabVisibility>();
            userPermissions = new List<UserPermission>();
        }
    }
    
    public class FieldPermission {
        public Boolean editable;
        public Boolean readable;
        public String field;
    }
    
    public class ObjectPermission {
        public Boolean allowCreate;
        public Boolean allowDelete;
        public Boolean allowEdit;
        public Boolean allowRead;
        public Boolean modifyAllRecords;
        public String objectName;
        public Boolean viewAllFields;
        public Boolean viewAllRecords;
    }
    
    public class TabVisibility {
        public String tab;
        public String visibility;
    }
    
    public class UserPermission {
        public Boolean enabled;
        public String name;
    }
    
    /**
     * Main method to process Profile XML and create custom object
     * @param xmlContent The Profile XML content
     */
    public static void processProfileXML(String xmlContent) {
        try {
            // Parse the XML
            ProfileData profileData = parseProfileXML(xmlContent);
            
            // Create the custom object
            createProfilesCustomObject();
            
            // Create dynamic fields based on the XML structure
            createDynamicFields(profileData);
            
            // Insert the profile record
            insertProfileRecord(profileData);
            
        } catch (Exception e) {
            System.debug('Error processing Profile XML: ' + e.getMessage());
            throw new ProfileXMLProcessorException('Error processing Profile XML: ' + e.getMessage());
        }
    }
    
    /**
     * Parse the Profile XML content
     */
    private static ProfileData parseProfileXML(String xmlContent) {
        ProfileData profileData = new ProfileData();
        
        // Create XML DOM
        Dom.Document doc = new Dom.Document();
        doc.load(xmlContent);
        Dom.XMLNode root = doc.getRootElement();
        
        // Parse basic profile information
        for (Dom.XMLNode child : root.getChildElements()) {
            String nodeName = child.getName();
            
            if (nodeName == 'description') {
                profileData.description = child.getText();
            } else if (nodeName == 'userLicense') {
                profileData.userLicense = child.getText();
            } else if (nodeName == 'custom') {
                profileData.custom = Boolean.valueOf(child.getText());
            } else if (nodeName == 'fieldPermissions') {
                FieldPermission fp = new FieldPermission();
                for (Dom.XMLNode fpChild : child.getChildElements()) {
                    String fpNodeName = fpChild.getName();
                    if (fpNodeName == 'editable') {
                        fp.editable = Boolean.valueOf(fpChild.getText());
                    } else if (fpNodeName == 'readable') {
                        fp.readable = Boolean.valueOf(fpChild.getText());
                    } else if (fpNodeName == 'field') {
                        fp.field = fpChild.getText();
                    }
                }
                profileData.fieldPermissions.add(fp);
            } else if (nodeName == 'objectPermissions') {
                ObjectPermission op = new ObjectPermission();
                for (Dom.XMLNode opChild : child.getChildElements()) {
                    String opNodeName = opChild.getName();
                    if (opNodeName == 'allowCreate') {
                        op.allowCreate = Boolean.valueOf(opChild.getText());
                    } else if (opNodeName == 'allowDelete') {
                        op.allowDelete = Boolean.valueOf(opChild.getText());
                    } else if (opNodeName == 'allowEdit') {
                        op.allowEdit = Boolean.valueOf(opChild.getText());
                    } else if (opNodeName == 'allowRead') {
                        op.allowRead = Boolean.valueOf(opChild.getText());
                    } else if (opNodeName == 'modifyAllRecords') {
                        op.modifyAllRecords = Boolean.valueOf(opChild.getText());
                    } else if (opNodeName == 'object') {
                        op.objectName = opChild.getText();
                    } else if (opNodeName == 'viewAllFields') {
                        op.viewAllFields = Boolean.valueOf(opChild.getText());
                    } else if (opNodeName == 'viewAllRecords') {
                        op.viewAllRecords = Boolean.valueOf(opChild.getText());
                    }
                }
                profileData.objectPermissions.add(op);
            } else if (nodeName == 'tabVisibilities') {
                TabVisibility tv = new TabVisibility();
                for (Dom.XMLNode tvChild : child.getChildElements()) {
                    String tvNodeName = tvChild.getName();
                    if (tvNodeName == 'tab') {
                        tv.tab = tvChild.getText();
                    } else if (tvNodeName == 'visibility') {
                        tv.visibility = tvChild.getText();
                    }
                }
                profileData.tabVisibilities.add(tv);
            } else if (nodeName == 'userPermissions') {
                UserPermission up = new UserPermission();
                for (Dom.XMLNode upChild : child.getChildElements()) {
                    String upNodeName = upChild.getName();
                    if (upNodeName == 'enabled') {
                        up.enabled = Boolean.valueOf(upChild.getText());
                    } else if (upNodeName == 'name') {
                        up.name = upChild.getText();
                    }
                }
                profileData.userPermissions.add(up);
            }
        }
        
        return profileData;
    }
    
    /**
     * Create the Profiles custom object
     */
    private static void createProfilesCustomObject() {
        // This would typically be done through metadata API or deployment
        // For now, we'll create the object definition in the metadata
        System.debug('Creating Profiles custom object...');
    }
    
    /**
     * Create dynamic fields based on the XML structure
     */
    private static void createDynamicFields(ProfileData profileData) {
        // Create picklist fields for each unique tag type
        Set<String> tagTypes = new Set<String>();
        
        if (!profileData.fieldPermissions.isEmpty()) {
            tagTypes.add('fieldPermissions');
        }
        if (!profileData.objectPermissions.isEmpty()) {
            tagTypes.add('objectPermissions');
        }
        if (!profileData.tabVisibilities.isEmpty()) {
            tagTypes.add('tabVisibilities');
        }
        if (!profileData.userPermissions.isEmpty()) {
            tagTypes.add('userPermissions');
        }
        
        // Create picklist field for tag types
        createPicklistField('Tag_Types__c', 'Tag Types', new List<String>(tagTypes));
        
        // Create fields for userPermissions
        if (!profileData.userPermissions.isEmpty()) {
            createBooleanField('User_Permission_Enabled__c', 'User Permission Enabled');
            createTextField('User_Permission_Name__c', 'User Permission Name', 255);
        }
        
        // Create fields for fieldPermissions
        if (!profileData.fieldPermissions.isEmpty()) {
            createBooleanField('Field_Permission_Editable__c', 'Field Permission Editable');
            createBooleanField('Field_Permission_Readable__c', 'Field Permission Readable');
            createTextField('Field_Permission_Field__c', 'Field Permission Field', 255);
        }
        
        // Create fields for objectPermissions
        if (!profileData.objectPermissions.isEmpty()) {
            createBooleanField('Object_Permission_AllowCreate__c', 'Object Permission Allow Create');
            createBooleanField('Object_Permission_AllowDelete__c', 'Object Permission Allow Delete');
            createBooleanField('Object_Permission_AllowEdit__c', 'Object Permission Allow Edit');
            createBooleanField('Object_Permission_AllowRead__c', 'Object Permission Allow Read');
            createBooleanField('Object_Permission_ModifyAllRecords__c', 'Object Permission Modify All Records');
            createTextField('Object_Permission_Object__c', 'Object Permission Object', 255);
            createBooleanField('Object_Permission_ViewAllFields__c', 'Object Permission View All Fields');
            createBooleanField('Object_Permission_ViewAllRecords__c', 'Object Permission View All Records');
        }
        
        // Create fields for tabVisibilities
        if (!profileData.tabVisibilities.isEmpty()) {
            createTextField('Tab_Visibility_Tab__c', 'Tab Visibility Tab', 255);
            createTextField('Tab_Visibility_Visibility__c', 'Tab Visibility Visibility', 255);
        }
    }
    
    /**
     * Create a picklist field
     */
    private static void createPicklistField(String apiName, String label, List<String> values) {
        System.debug('Creating picklist field: ' + apiName + ' with values: ' + values);
        // This would be implemented through metadata API
    }
    
    /**
     * Create a boolean field
     */
    private static void createBooleanField(String apiName, String label) {
        System.debug('Creating boolean field: ' + apiName);
        // This would be implemented through metadata API
    }
    
    /**
     * Create a text field
     */
    private static void createTextField(String apiName, String label, Integer length) {
        System.debug('Creating text field: ' + apiName + ' with length: ' + length);
        // This would be implemented through metadata API
    }
    
    /**
     * Insert the profile record with data from XML
     */
    private static void insertProfileRecord(ProfileData profileData) {
        // Create the Profiles__c record
        Profiles__c profileRecord = new Profiles__c();
        // Note: Name field is AutoNumber, so we don't set it
        profileRecord.Description__c = profileData.description;
        profileRecord.User_License__c = profileData.userLicense;
        profileRecord.Custom__c = profileData.custom;
        
        // Set tag types
        List<String> tagTypes = new List<String>();
        if (!profileData.fieldPermissions.isEmpty()) tagTypes.add('fieldPermissions');
        if (!profileData.objectPermissions.isEmpty()) tagTypes.add('objectPermissions');
        if (!profileData.tabVisibilities.isEmpty()) tagTypes.add('tabVisibilities');
        if (!profileData.userPermissions.isEmpty()) tagTypes.add('userPermissions');
        profileRecord.Tag_Types__c = String.join(tagTypes, ';');
        
        // Set user permission values (using first one as example)
        if (!profileData.userPermissions.isEmpty()) {
            UserPermission up = profileData.userPermissions[0];
            profileRecord.User_Permission_Enabled__c = up.enabled;
            profileRecord.User_Permission_Name__c = up.name;
        }
        
        // Set field permission values (using first one as example)
        if (!profileData.fieldPermissions.isEmpty()) {
            FieldPermission fp = profileData.fieldPermissions[0];
            profileRecord.Field_Permission_Editable__c = fp.editable;
            profileRecord.Field_Permission_Readable__c = fp.readable;
            profileRecord.Field_Permission_Field__c = fp.field;
        }
        
        // Set object permission values (using first one as example)
        if (!profileData.objectPermissions.isEmpty()) {
            ObjectPermission op = profileData.objectPermissions[0];
            profileRecord.Object_Permission_AllowCreate__c = op.allowCreate;
            profileRecord.Object_Permission_AllowDelete__c = op.allowDelete;
            profileRecord.Object_Permission_AllowEdit__c = op.allowEdit;
            profileRecord.Object_Permission_AllowRead__c = op.allowRead;
            profileRecord.Object_Permission_ModifyAllRecords__c = op.modifyAllRecords;
            profileRecord.Object_Permission_Object__c = op.objectName;
            profileRecord.Object_Permission_ViewAllFields__c = op.viewAllFields;
            profileRecord.Object_Permission_ViewAllRecords__c = op.viewAllRecords;
        }
        
        // Set tab visibility values (using first one as example)
        if (!profileData.tabVisibilities.isEmpty()) {
            TabVisibility tv = profileData.tabVisibilities[0];
            profileRecord.Tab_Visibility_Tab__c = tv.tab;
            profileRecord.Tab_Visibility_Visibility__c = tv.visibility;
        }
        
        // Insert the record
        insert profileRecord;
        System.debug('Profile record created with ID: ' + profileRecord.Id);
    }
    
    /**
     * Custom exception class
     */
    public class ProfileXMLProcessorException extends Exception {}
}